-- AlterTable
ALTER TABLE `users` ADD COLUMN `avatar` MEDIUMTEXT NULL,
    ADD COLUMN `bio` VARCHAR(200) NULL,
    ADD COLUMN `birthday` DATETIME(3) NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
